name: iptv_app
description: A Flutter IPTV application with MVVM and Riverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  video_player: ^2.8.6
  better_player: ^0.0.84
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/channels.json
    - assets/data/movies.json
    - assets/data/series.json
